### ISSUE TITLE
Index.js wrong file

### ISSUE THREAD

**Issue by cookednoodles** [tleunen/react-number-editor#20]
Index.js appears to be pointing to : ./lib/NumberEditor

However the file is in ./src/

**Comment by tleunen** [comment]
It's not an error, it's done on purpose. It's because the file gets compiled when the package is published on NPM. So the `lib/index.js` exists at that time.

**Comment by cookednoodles** [comment]
The v4 build doesn't seem to be doing this, there isn't a lib folder in the build.

**Comment by tleunen** [comment]
You're right. a `.npmignore` is required to prevent npm to use `.gitignore` which is ignoring `/lib`.
Reopening this issue.

**Comment by tleunen** [comment]
Should be fixed now with the version `4.0.1` :) Thanks again @cookednoodles!
