### ISSUE TITLE
Infinite loop when value prop is number

### ISSUE THREAD

**Issue by rumman23** [tleunen/react-number-editor#23]
Dragging causes infinite loop when value prop is passed as number(prop change fires onValueChange callback immediately). Same works well when prop is string.
I suspect that this is caused by strict comparison of values in _changeValue.

**Comment by tleunen** [comment]
Thanks for reporting the issue.
Any help is welcome to resolve it. I'm quite busy on another project for at least the next few days.
Also, we should add tests to prevent this from happening.
