### ISSUE TITLE
infinite loop w/ 2.2.0

### ISSUE THREAD

**Issue by KyleAMathews** [tleunen/react-number-editor#6]
Haven't dug too deep. 2.1.0 works just fine.

**Comment by tleunen** [comment]
Hmm.. The changes between 2.1 and 2.2 is that I removed the mixin for the click and drag feature and I replaced it with the new component for it.

Do you have a specific usecase so I can easily debug it?

**Comment by KyleAMathews** [comment]
I do actually :) I should have added this in my initial comment actually.

Clone https://github.com/KyleAMathews/typography.js and then run `npm install`. Then run `node_modules/.bin/webpack-dev-server` then open `localhost:8080`. Everything should work.

Then install the latest version of react-number-editor. Then when you try dragging on the controls on the left column, the UI will freeze. If you put a console.log in the componentDidUpdate of this module, then it'll show an infinite loop.

**Comment by tleunen** [comment]
I couldn't make it work. I'm on Windows right now.
I never used webpack before, but when I run the server, it doesn't seem to run in the right folder.

**Comment by tleunen** [comment]
Ok after installing webpack-dev-server globally, it's a bit better but I still can't run the project. The server is opened and serves the `examples` folder, and then what? I just see the list of files but nothing else.

**Comment by KyleAMathews** [comment]
Hrmm... I don't use Windows and don't have one that's easy to test with. What might work however is if you click the index.html file (if you see one?). If you feel up to playing with the webpack config file, the line that controls the default folder that gets served is line 11 in `webpack.config.js`. Perhaps the syntax there doesn't work with Windows.

**Comment by cranesandcaff** [comment]
Having same issue. I'll look into it as well. Is it ReactHotLoader somehow causing it?

**Comment by KyleAMathews** [comment]
Hmmm no I don't think so. I deployed the typography app to github (which
does a production build) and saw the same problem.

**Comment by cranesandcaff** [comment]
I installed v 2.1.0 and still got it. Are you sure 2.1.0 worked?

**Comment by KyleAMathews** [comment]
That's what's running at http://kyleamathews.github.io/typography.js/#/

**Comment by tleunen** [comment]
Ok I got the same result with a mac. The server is running but I don't have any index.html file.. Here is what I get:
![screen shot 2015-05-12 at 6 25 46 pm](https://cloud.githubusercontent.com/assets/1972567/7599939/693f16b0-f8d4-11e4-8238-2977ab4f3821.png)

Maybe you could create a small usecase which reproduce the issue?

**Comment by KyleAMathews** [comment]
Well that helped :) apparently I never checked in the index.html file. `git pull` and it should work now. Sorry for the bother!

**Comment by tleunen** [comment]
So the thing is: when you drag the value, it will change its internal state value and execute the `onChange` callback. When you receive the callback, your component changes its state which results in a re-render of the component (and so `react-number-editor` will receive new props, which results in a value change again, and here's the loop.

There is definitely something I have to fix here because it makes the entire component unusable. I'll try to take a look at this in the following days. And probably change how the component works as it is described in #5 as well.

**Comment by KyleAMathews** [comment]
ok, sounds great! Thanks!

**Comment by cranesandcaff** [comment]
Any update on this?

**Comment by cranesandcaff** [comment]
I was planning on forking and fixing this today, what is the purpose of converting the number to a string?

I was planning on just moving the value to a prop and fixing the issue by containing the inputs state in it's parent component.

**Comment by tleunen** [comment]
Wow sorry I completely forgot about this.
There is the controllable branch which should resolve most of the known issues https://github.com/tleunen/react-number-editor/tree/controllable

You can also submit PR for this branch if you see some errors in there. Let me know!
I'll merge it into master in the next days.

**Comment by cranesandcaff** [comment]
Awesome thanks, out of curiosity though, what was/is the value of casting to the string?

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by tleunen** [comment]
The string cast is to allow a custom display with a number of decimals (eg. 5.00 instead of 5).
It might be possible to extract this logic from the state and put the formatting inside the render function.

I don't have a lot of time right now but can take a look to improve the behavior in the next days. I'll reuse this component for a new project so I'll probably change a few things.

**Comment by cranesandcaff** [comment]
Still have an infinite loop on that branch. 

Why not `Number.toFixed()`? That should render the decimals I think...I'll check.

I'll submit a PR in a bit because I'm hoping to use this now.

I fixed the infinite loop issue, but I'm not sure if it matches the other things you wanted to change.

**Comment by tleunen** [comment]
Thanks for taking a look at this.

`Number.toFixed` is used to format the number ;)

**Comment by tleunen** [comment]
Release 3.0 now
