### ISSUE TITLE
react-native support ? 

### ISSUE THREAD

**Issue by mydearxym** [tleunen/react-number-editor#7]
amazing work!
is this component support react-native?

**Comment by tleunen** [comment]
Never tried React Native yet so I don't know. But because the syntax changed between simple React and React Native, I'm pretty sure it's not supported and would need a few changes

**Comment by KyleAMathews** [comment]
This module wouldn't work on IOS as it relies the DOM for touch support, etc.

**Comment by mydearxym** [comment]
thanks ~  maybe use  webView inside react-native is the better choice~
